// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9XPQhdmse2rNiNVCiRJLXpnZWH4GL0a0',
    appId: '1:1053529813962:web:0ee208a0f8273262509533',
    messagingSenderId: '1053529813962',
    projectId: 'failball',
    authDomain: 'failball.firebaseapp.com',
    storageBucket: 'failball.firebasestorage.app',
    measurementId: 'G-K2QQBZJ34T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Jp2VMA_qTsyzc8n37JIOxr4IK5z0PP0',
    appId: '1:1053529813962:android:e0053d4c678f5c49509533',
    messagingSenderId: '1053529813962',
    projectId: 'failball',
    storageBucket: 'failball.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLnpfqfS8J0iytblVNvIm7wZMQx_5YYi8',
    appId: '1:1053529813962:ios:21936028e8c1ea15509533',
    messagingSenderId: '1053529813962',
    projectId: 'failball',
    storageBucket: 'failball.firebasestorage.app',
    iosBundleId: 'com.example.failball',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLnpfqfS8J0iytblVNvIm7wZMQx_5YYi8',
    appId: '1:1053529813962:ios:21936028e8c1ea15509533',
    messagingSenderId: '1053529813962',
    projectId: 'failball',
    storageBucket: 'failball.firebasestorage.app',
    iosBundleId: 'com.example.failball',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9XPQhdmse2rNiNVCiRJLXpnZWH4GL0a0',
    appId: '1:1053529813962:web:378a74f290c77339509533',
    messagingSenderId: '1053529813962',
    projectId: 'failball',
    authDomain: 'failball.firebaseapp.com',
    storageBucket: 'failball.firebasestorage.app',
    measurementId: 'G-E6FZR8H9G0',
  );
}
